language: python
env:
  - TOXENV=py27
  - TOXENV=py35
  - TOXENV=pypy-5.3.1
  - TOXENV=doc
  - TOXENV=pep8
# upgrade setuptools to support environment markers
# in install_requires of setup.py
install: pip install -U setuptools tox
script: tox
notifications:
  email:
    - victor.stinner@gmail.com
