dist: bionic
language: python

jobs:
  fast_finish: true
  include:
    - python: '3.6'
      env: TOX_ENV=py36
    - python: '3.8'
      env: TOX_ENV=py38
    # - python: pypy3.5-5.10.1
    #   env: TOX_ENV=pypy3
    - python: nightly
      env: TOX_ENV=py3
    - python: '3.8'
      env: TOX_ENV=doc
    - python: '3.8'
      env: TOX_ENV=pep8
    # FIXME: At 2020-10-26, '3.9' is not accepted by Travis CI yet.
    # Python 3.9.0 was released at 2020-10-05.
    - python: '3.9-dev'
      env: TOX_ENV=py3

install:
    - travis_retry pip install tox tox-venv
    - python -VV

script:
    - "tox -e $TOX_ENV -- $TOX_ARGS"
